### ISSUE TITLE
Allow widgets to be added to FormDialog with spanning role

### ISSUE THREAD

**Issue by lauramurgatroyd** [paskino/qt-elements#10]
Currently, you can only add widgets to the form dialog if you have a label and widget - there is no option to add a single widget to span the form.
https://github.com/paskino/qt-elements/blob/85f34d68e9d655281720c2db549b48c3aea1547e/eqt/ui/FormDialog.py#L41-L53

 E.g. I would like to make a form that looks something like this:

![image](https://user-images.githubusercontent.com/60604372/115857652-d76e3000-a425-11eb-9ac4-b2ba0ad15917.png)

The checkboxes should have a spanning role, as they aren't a separate label and widget - currently to add them to the form dialog I have to create empty QLabels to go along with them.

It would also allow you to add a separator that spans the width of the form.

I propose:

- We add a kwarg to addWidget called layout. Default=form
- We allow only a widget and name to be set, without setting a label. In this case, we check the layout kwarg. If it's set to 'form' add it to the form, if it's set to 'vertical', we add it to the vertical layout below the form.

**Comment by paskino** [comment]
I think checkboxes are a special case, aren't they?

What about adding a test for type `QCheckBox` and in that case add the widget with spanning role?

Also for a separator it makes sense to have an `addSeparator` method.

However, I guess that a parameter `layout='form'` or `layout='vertical'` makes a lot of sense as it would make this behaviour clearer.
