### ISSUE TITLE
Add methods to UIFormWidget for saving and reinstating values of widgets

### ISSUE THREAD

**Issue by lauramurgatroyd** [paskino/qt-elements#61]
https://github.com/paskino/qt-elements/blob/3efa58cf7dc4f2bb87565d0165179805ff237b18/eqt/ui/UIFormWidget.py#L4

I think it would be best to save a dictionary with the name of the widget and its state

**Comment by lauramurgatroyd** [comment]
Make sure it can handle the following widget types:

- [ ] QLabels - save the current text
- [ ] QCheckBox - save whether checked
- [ ] QComboBox - save current index
- [ ] QDoubleSpinBox
- [ ] QSpinBox
- [ ] QPushButton
- [ ] QLineEdit
- [ ] UISliderWidget and/or QSlider

**Comment by lauramurgatroyd** [comment]
As well as their status (i.e. current value) we also want to save and be able to reload whether the widgets are enabled or not.
Should we have two dictionaries - one for widget values and one for widget enabled?

**Comment by paskino** [comment]
Or one with multiple info per widget?

**Comment by lauramurgatroyd** [comment]
Each widget could have a dict with 'status' and 'visibility' (is status the correct word to use?)

e.g.
settings = {'widget name' : {'status': True, 'visibility': False}}

**Comment by lauramurgatroyd** [comment]
Current code used for saving and restoring widgets in viewer toolbar dialogs is here:
https://github.com/Dagonite/CILViewer/blob/3c070b25fbbea7dc35bf8b77a21b784998e973d0/Wrappers/Python/ccpi/viewer/ui/SettingsDialog.py#L35-L59
